In [1]:
import numpy as np

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
a = np.array([])

In [3]:
a

array([], dtype=float64)

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [7]:
arr[0]

1

In [8]:
arr[-1]

10

In [9]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

a = np.arrange(6)

In [13]:
import numpy as np

In [16]:
a = np.arange(6)

In [17]:
a

array([0, 1, 2, 3, 4, 5])

In [18]:
a = a.reshape(3,2)

In [19]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
a = a.reshape(2,3)

In [21]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
np.reshape(a, (6,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [23]:
a = np.array([1, 2, 3, 4, 5, 6])

In [24]:
a.shape

(6,)

In [25]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


### 

In [26]:
a3 = a2[np.newaxis]
print(a3.shape)
print(a3)

(1, 1, 6)
[[[1 2 3 4 5 6]]]


In [28]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [29]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a